#!/usr/bin/env bash
# Displays username, user id, and home directory for each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r username _ uid _ home _
do
	echo "Username: $username"
	echo "User ID: $uid"
	echo "Home Directory: $home"
done < "$input"
