#!/usr/bin/env bash
# Parses an Apache log file and displays the IP and HTTP code for each visitor.

log_file="apache-access.log"

if [ -e "$log_file" ]; then
	awk '{print $1, $9}' "$log_file"
else
	echo "Error: $log_file does not exist."
fi
