#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

a=1
while (( a<=20 ))
do
	echo $a
	if (( a==4 ))
	then
		echo "bad luck from China"
	elif (( a==9 ))
	then
		echo "bad luck from Japan"
	elif (( a==17 ))
	then
		echo "bad luck from Italy"
	fi
	(( a++ ))
done
